### ISSUE TITLE
Не открываются файлы по ssh from windows

### ISSUE THREAD

**Issue by tiger-greyhawk** [sevdokimov/FriendlyTerminal#9]
Привет. Установил после статьи на Хабре себе на 2 виндовых компа под последнюю IDEA  community. 
Локальные файлы открываются нормально, а при попытке открытия файлов на удаленной системе по ssh пишет "Failed to download file".

![image](https://user-images.githubusercontent.com/8466748/219438858-2c9e43f7-5577-4aca-81fe-261e85d5e55d.png)

<quote>
IntelliJ IDEA 2022.3.2 (Community Edition)
Build #IC-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins:
    com.ess.terminal-pro (1.1.1)
    idea.plugin.protoeditor (223.8214.6)

Kotlin: 223-1.8.0-release-345-IJ8617.56
</quote>

На обоих машинах linux subsystem ставил уже после установки IDEA и данного плагина.

Не нашел куда плагин складирует логи.
Какая от меня еще информация требуется?

**Comment by sevdokimov** [comment]
@tiger-greyhawk ,
Привет,
Спасибо за подробный bug report.
Логи IntelliJ IDEA можно открыть нажав в главном меню `Help -> Show Log in Explorer` , там должен быть эксепшен, можете поискать по слову "DownloadedFileCacheService".
Вы подключались по ssh через кнопку SSH -> New SSH Connection или запустив коменду "ssh username@hostname" в командной строке?

**Comment by tiger-greyhawk** [comment]
2023-02-16 19:54:31,522 [  45844]   WARN - #c.i.o.a.i.ActionUpdater - 451 ms to grab EDT for ExpandAllAction#update@ToolwindowTitle (com.intellij.ide.actions.ExpandAllAction)
2023-02-16 19:54:32,894 [  47216]   INFO - #c.i.c.CompilerWorkspaceConfiguration - Available processors: 8
2023-02-16 19:54:35,465 [  49787]   INFO - #c.i.v.l.d.i.IndexDiagnosticRunner - Running index diagnostic for [file://G:/_src/Java/shold-secure-backup]
2023-02-16 19:54:37,170 [  51492]   INFO - #c.i.d.WindowsDefenderChecker - Windows Defender status: Failed to get excluded patterns
2023-02-16 19:54:40,341 [  54663] SEVERE - com.jediterm.terminal.model.TerminalTextBuffer - Attempt to get line out of bounds: 24 >= 24
2023-02-16 19:54:40,451 [  54773] SEVERE - com.jediterm.terminal.model.TerminalTextBuffer - Attempt to get line out of bounds: 23 >= 23
2023-02-16 19:54:57,245 [  71567] SEVERE - com.jediterm.terminal.model.TerminalTextBuffer - Attempt to get line out of bounds: 23 >= 23
2023-02-16 19:54:57,246 [  71568] SEVERE - com.jediterm.terminal.model.TerminalTextBuffer - Attempt to get line out of bounds: 23 >= 23
2023-02-16 19:54:57,287 [  71609] SEVERE - com.jediterm.terminal.model.TerminalTextBuffer - Attempt to get line out of bounds: 23 >= 23
2023-02-16 19:54:57,288 [  71610] SEVERE - com.jediterm.terminal.model.TerminalTextBuffer - Attempt to get line out of bounds: 23 >= 23
2023-02-16 19:54:59,375 [  73697] SEVERE - com.jediterm.terminal.model.LinesBuffer - Negative line number: -1
2023-02-16 19:55:03,402 [  77724] SEVERE - com.jediterm.terminal.model.LinesBuffer - Negative line number: -1
2023-02-16 19:55:06,477 [  80799] SEVERE - com.jediterm.terminal.model.LinesBuffer - Negative line number: -1
2023-02-16 19:55:06,507 [  80829] SEVERE - com.jediterm.terminal.model.LinesBuffer - Negative line number: -1
2023-02-16 19:55:06,601 [  80923]   WARN - #com.ess.intellij.terminal.uploading.DownloadedFileCacheService - Failed to download file, output: 
2023-02-16 19:55:06,607 [  80929]   WARN - #com.ess.intellij.terminal.uploading.DownloadedFileCacheService - Failed to download file
java.lang.RuntimeException: Failed to download file
	at com.ess.intellij.terminal.uploading.DownloadedFileCacheService.lambda$doDownloadFileAsync$18(DownloadedFileCacheService.java:829)
	at com.ess.intellij.terminal.utils.Utils.lambda$handlerInPooledThread$4(Utils.java:575)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-16 19:55:28,898 [ 103220]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2023-02-16 19:55:30,135 [ 104457]   WARN - #c.i.o.o.n.SettingsTreeView$MyBuilder - 'AbstractTreeBuilder' is going to be dropped soon and must not be used
com.intellij.diagnostic.PluginException: 'AbstractTreeBuilder' is going to be dropped soon and must not be used
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:60)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:55)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:47)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeBuilder.<init>(FilteringTreeBuilder.java:46)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyBuilder.<init>(SettingsTreeView.java:931)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:174)
	at com.intellij.openapi.options.newEditor.SettingsDialog.treeViewFactory(SettingsDialog.java:89)
	at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:194)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:65)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.java:38)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getDialog(ShowSettingsUtilImpl.java:39)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:289)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:64)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-02-16 19:55:42,018 [ 116340] SEVERE - #o.j.i.BuiltInServer - Программа на вашем хост-компьютере разорвала установленное подключение
java.io.IOException: Программа на вашем хост-компьютере разорвала установленное подключение
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:46)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:284)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:259)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:417)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-16 19:55:42,029 [ 116351] SEVERE - #o.j.i.BuiltInServer - IntelliJ IDEA 2022.3.2  Build #IC-223.8617.56
2023-02-16 19:55:42,030 [ 116352] SEVERE - #o.j.i.BuiltInServer - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-02-16 19:55:42,034 [ 116356] SEVERE - #o.j.i.BuiltInServer - OS: Windows 10
2023-02-16 19:55:42,042 [ 116364]   INFO - #o.j.i.BuiltInServer - Channel will be closed due to error

**Comment by tiger-greyhawk** [comment]
подключался через ssh login@ip

**Comment by sevdokimov** [comment]
Проблему воспроизвёл, разберусь, спасибо.

**Comment by tiger-greyhawk** [comment]
Тебе огромное спасибо за такую идею и реализацию. Подправить конфиг на удаленной машине гораздо приятнее через любимую IDEA )
Буду ждать исправления.

**Comment by tiger-greyhawk** [comment]
еще не понял про какую "через кнопку SSH -> New SSH Connection". Возможно у меня данный функционал тоже не отображается.
 ++ нет автоподстановки предыдущих команд подключения как на демо-видео:
![image](https://user-images.githubusercontent.com/8466748/219448728-60fe2736-77b8-4818-8943-e5432ed1a8ea.png)

у меня вот так:
![image](https://user-images.githubusercontent.com/8466748/219448882-1da8c69f-4f2d-42e8-a7db-60354241bc64.png)


ЗЫ версия плагина последняя 1.1.1

**Comment by sevdokimov** [comment]
Эта кнопка есть только в IDEA Ultimate. IDEA Ultimate сама умеет работать с SSH, у неё в конфигурации можно задать список SSH connection, и эта кнопка открывает коннекшен из идеевской конфигурации. В IDEA Community такого нет.

**Comment by sevdokimov** [comment]
Исправил, в версии 1.1.2 должно работать
